### ISSUE TITLE
How do we run the code? please provide Trained model 

### ISSUE THREAD

**Issue by pramodyn** [yulinliu101/DeepTP#2]

**Comment by yulinliu101** [comment]
The pre-trained model can be found at: https://github.com/yulinliu101/DeepTP/tree/master/src/nn/session

Currently some paths to the data in the ```Run_RNN_model_Lite.py``` have not been changed and you may want to alter them. Also, inference is currently only possible for flights from 2013/08/16 12:00 -- 18:00 UTC due to the significant size of the wind dataset. However the training process can be done without much alternations in the code.
